// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5AA4FRmidIfJUWd1oeD6TbWRULBDN0aU',
    appId: '1:529314975308:web:5028f284f851970a50eee9',
    messagingSenderId: '529314975308',
    projectId: 'qoute-8e7ce',
    authDomain: 'qoute-8e7ce.firebaseapp.com',
    storageBucket: 'qoute-8e7ce.firebasestorage.app',
    measurementId: 'G-W6JJ9H3V9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnpQuogZrj4GHq6JGU3VI-GouPXQ8G9qQ',
    appId: '1:529314975308:android:f3a11937678c154050eee9',
    messagingSenderId: '529314975308',
    projectId: 'qoute-8e7ce',
    storageBucket: 'qoute-8e7ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBek9C9AGOe8VkxSaObMUCbAMajXPfbjBU',
    appId: '1:529314975308:ios:a526732056c4da3550eee9',
    messagingSenderId: '529314975308',
    projectId: 'qoute-8e7ce',
    storageBucket: 'qoute-8e7ce.firebasestorage.app',
    iosBundleId: 'com.example.widgetSpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBek9C9AGOe8VkxSaObMUCbAMajXPfbjBU',
    appId: '1:529314975308:ios:a526732056c4da3550eee9',
    messagingSenderId: '529314975308',
    projectId: 'qoute-8e7ce',
    storageBucket: 'qoute-8e7ce.firebasestorage.app',
    iosBundleId: 'com.example.widgetSpace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5AA4FRmidIfJUWd1oeD6TbWRULBDN0aU',
    appId: '1:529314975308:web:acf08c1771b26bd550eee9',
    messagingSenderId: '529314975308',
    projectId: 'qoute-8e7ce',
    authDomain: 'qoute-8e7ce.firebaseapp.com',
    storageBucket: 'qoute-8e7ce.firebasestorage.app',
    measurementId: 'G-W18DG86PJZ',
  );
}
